---
ios_devices:
    platform: ios
    connection_options:
      scrapli:
        platform: cisco_iosxe
        extras:
          auth_strict_key: False
          transport: system
          transport_options: {"open_cmd": ["-o", "KexAlgorithms=+diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1", "-o", "Ciphers=+aes256-cbc"]}

nxos_devices:
    platform: nxos_ssh
    connection_options:
      scrapli:
        platform: cisco_nxos
        extras:
          auth_strict_key: False
          transport: system
          transport_options: {"open_cmd": ["-o", "KexAlgorithms=+diffie-hellman-group1-sha1"]}

routers:
    platform: "ios"
    connection_options:
      scrapli:
        platform: cisco_iosxe
        extras:
          auth_strict_key: False
          transport: system
          transport_options: {"open_cmd": ["-o", "KexAlgorithms=+diffie-hellman-group1-sha1"]}

unmanaged_devices:
  {}

ap_devices:
  {}

ws_c2960s:
  {}

ws_c3560x:
  {}

ws_c2960x:
 {}

ws_c3750g:
 {}
