---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "network_automation/mac_finder/mac_finder/inventory/hosts.yml"
    group_file: "network_automation/mac_finder/mac_finder/inventory/groups.yml"
    defaults_file: "network_automation/mac_finder/mac_finder/inventory/defaults.yml"

runner:
  plugin: threaded
  options:
    num_workers: 650