#! /usr/bin/env python
"""
Creates the views (routes) for the secondary app
"""
from decouple import config
from flask import render_template
from network_automation.nw_infra_links import nw_infra_links

### VARIABLES ###
template_dir = "nw_infra_links"
FLS_GUEST_SPONSOR_URL = config("FLS_GUEST_SPONSOR_URL")
ATEA_PORTAL_URL = config("ATEA_PORTAL_URL")
ISE_PORTAL_URL = config("ISE_PORTAL_URL")
NEW_PRIME_PORTAL_URL = config("NEW_PRIME_PORTAL_URL")
OLD_PRIME_PORTAL_URL = config("OLD_PRIME_PORTAL_URL")
CPH_DNAC_PORTAL_URL = config("CPH_DNAC_PORTAL_URL")
CPH_CMIC_PORTAL_URL = config("CPH_CMIC_PORTAL_URL")
SLC_DNAC_PORTAL_URL = config("SLC_DNAC_PORTAL_URL")
SLC_CMIC_PORTAL_URL = config("SLC_CMIC_PORTAL_URL")
VMANAGE_PORTAL_URL = config("VMANAGE_PORTAL_URL")
UMBRELLA_PORTAL_URL = config("UMBRELLA_PORTAL_URL")
CCSP_PORTAL_URL = config("CCSP_PORTAL_URL")
CPH_MAIN_WLC_PORTAL_URL = config("CPH_MAIN_WLC_PORTAL_URL")
PER_MAIN_WLC_PORTAL_URL = config("PER_MAIN_WLC_PORTAL_URL")
EXCEL_IPAM_URL = config("EXCEL_IPAM_URL")
LANSWEEPER_PORTAL_URL = config("LANSWEEPER_PORTAL_URL")
CPH_OPMANAGER_PORTAL_URL = config("CPH_OPMANAGER_PORTAL_URL")
MAA_OPMANAGER_PORTAL_URL = config("MAA_OPMANAGER_PORTAL_URL")
ABE_OPMANAGER_PORTAL_URL = config("ABE_OPMANAGER_PORTAL_URL")
PANORAMA_PORTAL_URL = config("PANORAMA_PORTAL_URL")
CPH_VSPHERE_URL = config("CPH_VSPHERE_URL")
MAA_VSPHERE_URL = config("MAA_VSPHERE_URL")
ABE_VSPHERE_URL = config("ABE_VSPHERE_URL")
SLC_VSPHERE_URL = config("SLC_VSPHERE_URL")

### VIEW TO CREATE DATA ###
@nw_infra_links.route("/home")
def home():
    return render_template(
        f"{template_dir}/home.html",
        FLS_GUEST_SPONSOR_URL=FLS_GUEST_SPONSOR_URL,
        ATEA_PORTAL_URL=ATEA_PORTAL_URL,
        ISE_PORTAL_URL=ISE_PORTAL_URL,
        NEW_PRIME_PORTAL_URL=NEW_PRIME_PORTAL_URL,
        OLD_PRIME_PORTAL_URL=OLD_PRIME_PORTAL_URL,
        CPH_DNAC_PORTAL_URL=CPH_DNAC_PORTAL_URL,
        CPH_CMIC_PORTAL_URL=CPH_CMIC_PORTAL_URL,
        SLC_DNAC_PORTAL_URL=SLC_DNAC_PORTAL_URL,
        SLC_CMIC_PORTAL_URL=SLC_CMIC_PORTAL_URL,
        VMANAGE_PORTAL_URL=VMANAGE_PORTAL_URL,
        UMBRELLA_PORTAL_URL=UMBRELLA_PORTAL_URL,
        CCSP_PORTAL_URL=CCSP_PORTAL_URL,
        CPH_MAIN_WLC_PORTAL_URL=CPH_MAIN_WLC_PORTAL_URL,
        PER_MAIN_WLC_PORTAL_URL=PER_MAIN_WLC_PORTAL_URL,
        EXCEL_IPAM_URL=EXCEL_IPAM_URL,
        LANSWEEPER_PORTAL_URL=LANSWEEPER_PORTAL_URL,
        CPH_OPMANAGER_PORTAL_URL=CPH_OPMANAGER_PORTAL_URL,
        MAA_OPMANAGER_PORTAL_URL=MAA_OPMANAGER_PORTAL_URL,
        ABE_OPMANAGER_PORTAL_URL=ABE_OPMANAGER_PORTAL_URL,
        PANORAMA_PORTAL_URL=PANORAMA_PORTAL_URL,
        CPH_VSPHERE_URL=CPH_VSPHERE_URL,
        MAA_VSPHERE_URL=MAA_VSPHERE_URL,
        ABE_VSPHERE_URL=ABE_VSPHERE_URL,
        SLC_VSPHERE_URL=SLC_VSPHERE_URL,
    )